### PR TITLE
Iterate documents and display their data

### PR DESCRIPTION
**Pull request by jeromegamez**
I hope this helps!

:octocat:

### CODE REVIEW

**Comment by Sheld0n-Cooper** [comment]
Yes thank you Jérôme!

**Comment by jeromegamez** [comment]
How about this, you create some issues here in the repo when you're stuck and ping me about them - I can't promise too much, but if I can, I'll do then a PR addressing the issue, and you can merge it 🤞

**Comment by jeromegamez** [comment]
By the way, I'm using PHPStorm for Coding - it costs money, but it's so good - and there are also free EAP versions... they're alpha versions but usually work quite well, at least for me.

https://www.jetbrains.com/phpstorm/nextversion/

I'm saying this because I make use of intellisense and clicking through the methods a lot in it to discover the APIs of 3rd party libraries. There's certainly something similar for VS Code or other editors, it's just all I know and I find it really valuable.

This all just in case you didn't know already, I usually try to limit the amount of unasked advice 🙈, but especially with the Google Libraries, it helps me personally a lot

**Comment by Sheld0n-Cooper** [comment]
Thank you so much !
Ok, when I get stuck I'll put it on the repo.

I am using VS code I found an intellisense extension, thanks.

**Comment by Sheld0n-Cooper** [comment]
Hello Jerome,

I manage to add, modify and delete. No problem.

When you'll have the time. Can you give me an example to add a user with this method:

https://firebase-php.readthedocs.io/en/5.14.1/user-management.html

I created a "users" collection.
I tried something on the master branch.

**Comment by jeromegamez** [comment]
The users here are only available and accessible in https://console.firebase.google.com/project/_/authentication/users and they are not automatically persisted somewhere in Firestore/the realtime database.

You can still do this, it just has to be manually 😅, for example, you could do, after user creation:

```php
try {
    $createdUser = $auth->createUser($userProperties);
} catch (Throwable $e) { // Happens for example if the email is already taken
    echo $e->getMessage();
    exit;
}

$database->collection('users')->document($createdUser->uid)->set([
    'avatar' => 'https://i.pravatar.cc/300', // assign random avatar until the user chooses one
    // more properties
]);
```

Just because I remembered it, here's some more insight into the Auth database: https://stackoverflow.com/questions/50418497/how-to-populate-identifier-and-providers-in-firebase-custom-authentication/50549562#50549562

**Comment by Sheld0n-Cooper** [comment]
Okay that's good ! Thank you so much !

(The link you gave me on stackoverflow helped me but I had to adapt the code)

I used this method: 

```
<?php

declare(strict_types=1);

use Kreait\Firebase\Factory;
use Kreait\Firebase\Util\JSON;

require_once __DIR__.'/vendor/autoload.php';

$factory = (new Factory)->withServiceAccount(__DIR__.'/secret/test-cb42f-f9d8f278b806.json');

$auth = $factory->createAuth();

// Remove all users
/*
foreach ($auth->listUsers() as $user) {
    $auth->deleteUser($user->uid);
}
*/

$userProperties = [
    'email' => 'user2@example.com',
    'emailVerified' => false,
    'phoneNumber' => '+15555450100',
    'password' => 'secretPassword',
    'displayName' => 'John Doe',
    'photoUrl' => 'http://www.example.com/test/photo.png',
    'disabled' => false,
];

$createdUser = $auth->createUser($userProperties);
```

**Comment by Sheld0n-Cooper** [comment]
Hello jerome!

I can't connect using this method:

```
<?php

declare(strict_types=1);

use Kreait\Firebase\Factory;
use Kreait\Firebase\Util\JSON;

require_once __DIR__.'/vendor/autoload.php';

$factory = (new Factory)->withServiceAccount(__DIR__.'/secret/test-cb42f-f9d8f278b806.json');

$auth = $factory->createAuth();

$actionCodeSettings = [
    'continueUrl' => 'http://localhost/zone42/testfirebase/page2.php'
];

$auth->sendSignInWithEmailLink('jon-snow69955@yahoo.fr', $actionCodeSettings);
```

Normally I should be redirected to : _http://localhost/zone42/testfirebase/page2.php_

I have an error:

_Fatal error: Uncaught Kreait\Firebase\Auth\SendActionLink\FailedToSendActionLink: OPERATION_NOT_ALLOWED in C:\wamp64\www\zone42\testfirebase\vendor\kreait\firebase-php\src\Firebase\Auth\SendActionLink\FailedToSendActionLink.php on line 32
Kreait\Firebase\Auth\SendActionLink\FailedToSendActionLink: OPERATION_NOT_ALLOWED in C:\wamp64\www\zone42\testfirebase\vendor\kreait\firebase-php\src\Firebase\Auth\SendActionLink\FailedToSendActionLink.php on line 32_

Can you help me please?

Thank you.

**Comment by jeromegamez** [comment]
Not sure what that could be... Do you get the email but the link in it causes that error, or does the error happen when you click on the link?

**Comment by jeromegamez** [comment]
One request please: could you create a new issue per problem, with an extra test file? That would it make easier to follow the individual problems at Hand 🙏😅

**Comment by Sheld0n-Cooper** [comment]
Sorry it's because I probably didn't activate the option for the connection by email ...

Anyway, what I want is a login with password. I succeeded, everything is ok!

I give the code but everything works correctly:

```
<?php

declare(strict_types=1);

use Kreait\Firebase\Factory;
use Kreait\Firebase\Util\JSON;

require_once __DIR__.'/vendor/autoload.php';

$factory = (new Factory)->withServiceAccount(__DIR__.'/secret/test-user-10d38-e2a4aa3e9971.json');

$auth = $factory->createAuth();

try {
    $user = $auth->signInWithEmailAndPassword('test@yahoo.fr', 'mpd123456');
    $userData = $user->data();
    $localId = $userData['localId'];
    if ($user) { echo 'connected '. $localId; } // $localId go in the $_SESSION 

} catch (Throwable $e) {
    echo $e->getMessage();
    exit;
}
```

Ok, in the future I will create a new issue per problem on this repo.
I don't know much about github.

Thank you Jerome !

**Comment by jeromegamez** [comment]
I'm not sure I fully understand, but try this:

```php
<?php

declare(strict_types=1);

use Kreait\Firebase\Factory;

require_once __DIR__.'/vendor/autoload.php';

$factory = (new Factory)->withServiceAccount(__DIR__.'/secret/test-cb42f-f9d8f278b806.json');

$auth = $factory->createAuth();

$randomString = bin2hex(random_bytes(5));
$email = "test+{$randomString}@example.com";
$password = $randomString;

echo "Creating test user\n\n";
$testUser = $auth->createUserWithEmailAndPassword($email, $password);

echo "Trying to sign in user with email and password\n\n";

try {
    // Now using the test user's UserRecord object for the email
    $signInResult = $auth->signInWithEmailAndPassword($testUser->email, $password);

    $userId = $signInResult->firebaseUserId();

    echo "Sign In result:\n\n";
    print_r($signInResult->data());

    echo "User details:\n\n";
    $userRecord = $auth->getUser($userId);
    print_r($userRecord);

} catch (Throwable $e) {
    echo "Error received: {$e->getMessage()}\n\n";
    echo $e->getMessage();
}

echo "\n\nDeleting test user again...";
$auth->deleteUser($testUser->uid);
echo "DONE!\n\n";
```

**Comment by jeromegamez** [comment]
This should give you something like this:

grafik

Please note that `print_r()` is not the best tool for the job, I just made it quick and dirty 😅

**Comment by Sheld0n-Cooper** [comment]
Hello jerome!

Yes I understand. it works.

Thank you so much!

**Pull request closed without merging**
